name: Daily
on:
  # Runs midnight EAT/UTC+3 every day
  schedule:
    - cron: '10 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install requirements
        run: pip install -r Scripts/requirements.txt

      - name: Run Wordle script
        run: |
          python Scripts/daily.py
